### ISSUE TITLE
Serve this code as a python pip package

### ISSUE THREAD

**Issue by mfeliu** [idanmo/python-memcached-udp#3]
Hi. I have found this repository trying to help solving a [need](http://stackoverflow.com/questions/36374750/memcached-listeing-on-udp-with-django/36488619#36488619) related to Django cache backends. Maybe, it would me more useful this code if it was packed into a python pip package.

What do you think?

**Comment by idanmo** [comment]
Sounds good, will take care of it.
Thanks,
Idan

**Comment by idanmo** [comment]
Available on pypi: **python-memcached-udp**

The implementation is pretty basic, I can add more features if needed.

Thanks,
Idan
